"""D1_citizen_privacy

Revision ID: 9d7c4b69148d
Revises: bb91123ae763
Create Date: 2026-03-17 03:17:25.829728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d7c4b69148d'
down_revision: Union[str, Sequence[str], None] = 'bb91123ae763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leader_verification_requests_id'), table_name='leader_verification_requests')
    op.drop_table('leader_verification_requests')
    op.drop_index(op.f('ix_admin_notifications_id'), table_name='admin_notifications')
    op.drop_table('admin_notifications')
    op.drop_index(op.f('ix_leader_stances_id'), table_name='leader_stances')
    op.drop_index(op.f('ix_leader_stances_speaker_id'), table_name='leader_stances')
    op.drop_index(op.f('ix_leader_stances_topic'), table_name='leader_stances')
    op.drop_table('leader_stances')
    op.drop_index(op.f('ix_speaker_credential_vault_id'), table_name='speaker_credential_vault')
    op.drop_table('speaker_credential_vault')
    op.add_column('baraza_forum_comments', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.add_column('baraza_forum_posts', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.add_column('baraza_meetings', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.add_column('baraza_polls', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.alter_column('speakers', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('speakers', 'education',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('speakers', 'experience',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('speakers', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('speakers', 'constituency_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('speakers', 'county_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_speech_segments_bill_id'), table_name='speech_segments')
    op.drop_constraint(op.f('speech_segments_bill_id_fkey'), 'speech_segments', type_='foreignkey')
    op.drop_column('speech_segments', 'bill_id')
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_anonymous_default', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['display_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_anonymous_default')
    op.drop_column('users', 'display_name')
    op.add_column('speech_segments', sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('speech_segments_bill_id_fkey'), 'speech_segments', 'bills', ['bill_id'], ['id'])
    op.create_index(op.f('ix_speech_segments_bill_id'), 'speech_segments', ['bill_id'], unique=False)
    op.alter_column('speakers', 'county_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('speakers', 'constituency_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('speakers', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('speakers', 'experience',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('speakers', 'education',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('speakers', 'bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('baraza_polls', 'is_anonymous')
    op.drop_column('baraza_meetings', 'is_anonymous')
    op.drop_column('baraza_forum_posts', 'is_anonymous')
    op.drop_column('baraza_forum_comments', 'is_anonymous')
    op.create_table('speaker_credential_vault',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('speaker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maisha_namba_encrypted', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('staff_id_encrypted', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('speaker_credential_vault_speaker_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('speaker_credential_vault_pkey')),
    sa.UniqueConstraint('speaker_id', name=op.f('speaker_credential_vault_speaker_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_speaker_credential_vault_id'), 'speaker_credential_vault', ['id'], unique=False)
    op.create_table('leader_stances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('speaker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stance', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('consistency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date_recorded', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('evidence_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('leader_stances_speaker_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leader_stances_pkey'))
    )
    op.create_index(op.f('ix_leader_stances_topic'), 'leader_stances', ['topic'], unique=False)
    op.create_index(op.f('ix_leader_stances_speaker_id'), 'leader_stances', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_leader_stances_id'), 'leader_stances', ['id'], unique=False)
    op.create_table('admin_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_notifications_pkey'))
    )
    op.create_index(op.f('ix_admin_notifications_id'), 'admin_notifications', ['id'], unique=False)
    op.create_table('leader_verification_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('speaker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maisha_card_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('staff_card_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('leader_verification_requests_speaker_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('leader_verification_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leader_verification_requests_pkey'))
    )
    op.create_index(op.f('ix_leader_verification_requests_id'), 'leader_verification_requests', ['id'], unique=False)
    # ### end Alembic commands ###
