"""Add Bill and BillImpact models

Revision ID: bb91123ae763
Revises: f08984825288
Create Date: 2026-02-25 11:09:33.707946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb91123ae763'
down_revision: Union[str, Sequence[str], None] = 'f08984825288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_index(op.f('ix_bills_title'), 'bills', ['title'], unique=False)
    op.create_table('hansards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hansards_id'), 'hansards', ['id'], unique=False)
    op.create_index(op.f('ix_hansards_source_id'), 'hansards', ['source_id'], unique=True)
    op.create_index(op.f('ix_hansards_title'), 'hansards', ['title'], unique=False)
    op.create_table('bill_impacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('archetype', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_impacts_archetype'), 'bill_impacts', ['archetype'], unique=False)
    op.create_index(op.f('ix_bill_impacts_bill_id'), 'bill_impacts', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_impacts_id'), 'bill_impacts', ['id'], unique=False)
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('constituency_id', sa.Integer(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_id'), 'speakers', ['id'], unique=False)
    op.create_index(op.f('ix_speakers_name'), 'speakers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('id_number', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('constituency_id', sa.Integer(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('push_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_speaker_id'), 'subscriptions', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_topic'), 'subscriptions', ['topic'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_wards_id'), table_name='wards')
    op.drop_index(op.f('ix_wards_name'), table_name='wards')
    op.drop_table('wards')
    op.add_column('speech_segments', sa.Column('speaker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'speech_segments', 'speakers', ['speaker_id'], ['id'])
    op.create_foreign_key(None, 'speech_segments', 'hansards', ['hansard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'speech_segments', type_='foreignkey')
    op.drop_constraint(None, 'speech_segments', type_='foreignkey')
    op.drop_column('speech_segments', 'speaker_id')
    op.create_table('wards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('constituency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], name=op.f('wards_constituency_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wards_pkey'))
    )
    op.create_index(op.f('ix_wards_name'), 'wards', ['name'], unique=False)
    op.create_index(op.f('ix_wards_id'), 'wards', ['id'], unique=False)
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_topic'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_speaker_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_speakers_name'), table_name='speakers')
    op.drop_index(op.f('ix_speakers_id'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_bill_impacts_id'), table_name='bill_impacts')
    op.drop_index(op.f('ix_bill_impacts_bill_id'), table_name='bill_impacts')
    op.drop_index(op.f('ix_bill_impacts_archetype'), table_name='bill_impacts')
    op.drop_table('bill_impacts')
    op.drop_index(op.f('ix_hansards_title'), table_name='hansards')
    op.drop_index(op.f('ix_hansards_source_id'), table_name='hansards')
    op.drop_index(op.f('ix_hansards_id'), table_name='hansards')
    op.drop_table('hansards')
    op.drop_index(op.f('ix_bills_title'), table_name='bills')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
